baseurl = "http://caseybecking.com/"
languageCode = "en-us"
title = "Casey Becking"
author = "Casey Becking"
# Shown in the side menu
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10
theme = "blackburn"


[indexes]
  tag = "tags"
  topic = "topics"

[params]
  subtitle = "DevOps Engineer"
  brand = "Casey Becking"
  googleAnalytics = "UA-4281268-1"
  highlightjs = "androidstudio"
  description = "Learn more about Casey Becking"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

# SNS career oriented
  linkedin = "caseybecking"

  # SNS microblogging
  twitter = "caseybecking"

  # SNS photo/video sharing
  instagram = "caseybecking"

  

  # SNS news
  # reddit = "*"

  # Techie
  github = "caseybecking"

  stackoverflow = "145928/casey-becking"

  # Music
  # lastfm = "cbecking"
